# Generated by Django 5.1.7 on 2025-03-26 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.forum'),
        ),
    ]
